# Docs workflow
#
# Ensures that the docs can be built with sphinx.
# - On every push and PR, checks the HTML documentation builds on linux.
# - On every PR and tag, checks the documentation builds as a PDF on linux.

name: docs

on: [push, pull_request]

jobs:
  docs-html:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Build HTML docs
      uses: ammaraskar/sphinx-action@master
      with:
        docs-folder: "docs/"
        pre-build-command: "apt-get update -y && apt-get install -y binutils"
